language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
install: 
    - "pip install ."
    - "pip install coverage"
script:
    - "nosetests --with-coverage --cover-package=mdx_superscript"
